version: "3.3"
services:

  app:
    container_name: node-js-project
    image: node:14.0
    working_dir: /home/nodejsPro
    command: >
      bash -c "npm install
      && nodemon ./bin/www"
    ports:
       - 8082:8082
    volumes:
      - ./:/home/nodejsPro
